OnlineShop/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineShop.Data;
using OnlineShop.Data.Migrations;
using OnlineShop.Models;
using System.IO;



namespace OnlineShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _env;
        public ProductController(ApplicationDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public IActionResult Index()
        {
            return View(_context.Products.Include(p => p.ProductTypes).Include(s=>s.SpecialTag).ToList());
        }
        //Post Index action method
        [HttpPost]
        public IActionResult Index(decimal? lowAmount,decimal? largeamount)
        {
            var products=_context.Products.Include(p => p.ProductTypes).Include(s => s.SpecialTag).Where(c=>c.Price>=lowAmount && c.Price<=largeamount).ToList();
            if(lowAmount== null || largeamount== null)
            {
                products = _context.Products.Include(p => p.ProductTypes).Include(s => s.SpecialTag).ToList();
            }
            return View(products);
        }

        public IActionResult Create()
        {
            ViewData["ProTId"] = new SelectList(_context.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["STId"] = new SelectList(_context.SpecialTags.ToList(), "Id", "SpecialTagName");
            return View();
        }
        //Create post method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Products products, IFormFile image)
        {
  
            if (image != null && image.Length > 0)
              {
               // Save the uploaded image to disk
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Images", image.FileName);
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                   await image.CopyToAsync(stream);
                  products.Image = "Images/" + image.FileName;
                }
                if (image==null)
                {
                    products.Image = "Image/noimage.png";
                }
                 _context.Products.Add(products);
                 await _context.SaveChangesAsync();
                 return RedirectToAction("Index");
             }

            return View(products);
        }
        //Edit 
        public IActionResult Edit(int? id)
        {
            ViewData["ProTId"] = new SelectList(_context.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["STId"] = new SelectList(_context.SpecialTags.ToList(), "Id", "SpecialTagName");
            if (id == null)
            {
                return NotFound();

            }
            var product = _context.Products.Include(c=>c.ProductTypes).Include(c=>c.SpecialTag)
                .FirstOrDefault(c=>c.Id==id);
            if (product== null)
            {
                return NotFound();
            }
            return View(product);
        }
       // edit post method
        [HttpPost]
        public async Task<IActionResult> Edit(Products products, IFormFile image)
        {
           if(ModelState.IsValid)
           {
                if (image != null)
                {
                    var im = Path.Combine(_env.WebRootPath + "/Images", Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(im, FileMode.Create));

                    //var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Images", image.FileName);
                    //using (var stream = new FileStream(filePath, FileMode.Create))
                    //await image.CopyToAsync(stream);
                    products.Image = "Images/" + image.FileName;   
                }
                if (image == null)
                {
                    products.Image = "Image/noimage.png";
                }
                _context.Products.Update(products);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
              }

            return View(products);
        }
        //Details
       
        public IActionResult Detail(int ? id)
        {
            ViewData["ProTId"] = new SelectList(_context.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["STId"] = new SelectList(_context.SpecialTags.ToList(), "Id", "SpecialTagName");
            if (id==null)
            {
                return NotFound();
            }
            var product = _context.Products.Include(c=>c.ProductTypes).Include(c=>c.SpecialTag)
               .FirstOrDefault(c=>c.Id==id);
            if(product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        //Delete
        public IActionResult Delete(int? id)
        {

            ViewData["ProTId"] = new SelectList(_context.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["STId"] = new SelectList(_context.SpecialTags.ToList(), "Id", "SpecialTagName");
            if (id == null)
            {
                return NotFound();

            }
            var product = _context.Products.Include(c => c.ProductTypes).Include(c => c.SpecialTag)
                 .Where(c => c.Id == id).FirstOrDefault();
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }
        //Delet post method
        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int? id)
        {
            if(id==null)
            {
                return NotFound();
            }
            var product = _context.Products.FirstOrDefault(x => x.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
           return RedirectToAction("Index");
        }


    }
}

OnlineShop/Areas/Admin/Controllers/SpecialTagController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Data;
using OnlineShop.Models;

namespace OnlineShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SpecialTagController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SpecialTagController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {

            return View(_context.SpecialTags.ToList());
        }

        //Create Get

        public IActionResult Create()
        {
            return View();
        }
        //Create post method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SpecialTag specialTag)
        {
            if (ModelState.IsValid)
            {
                _context.SpecialTags.Add(specialTag);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(specialTag);
        }

        //Edit 
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();

            }
            var specialTag = _context.SpecialTags.Find(id);
            if (specialTag == null)
            {
                return NotFound();
            }
            return View(specialTag);
        }
        //edit post method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(SpecialTag specialTag)
        {
            if (ModelState.IsValid)
            {
                _context.SpecialTags.Update(specialTag);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(specialTag);
        }
        //Details
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();

            }
            var specialTag = _context.SpecialTags.Find(id);
            if (specialTag == null)
            {
                return NotFound();
            }
            return View(specialTag);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(SpecialTag specialTag)
        {
            return RedirectToAction(nameof(Index));

        }
        //Delete
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();

            }
            var specialTag = _context.SpecialTags.Find(id);
            if (specialTag == null)
            {
                return NotFound();
            }
            return View(specialTag);
        }
        //edit post method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id, SpecialTag specialTag)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (id != specialTag.Id)
            {
                return NotFound();
            }
            var st = _context.SpecialTags.Find(id);
            if (st == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _context.Remove(st);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(st);
        }

    }
}

OnlineShop/Views/Shared/_ButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<td style="width: 150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="ProductTypes" class="btn btn-success" asp-route-id="@Model">Edit</a>
        <a asp-action="Detail" asp-controller="ProductTypes" class="btn btn-info" asp-route-id="@Model">Details</a>
        <a asp-action="Delete" asp-controller="ProductTypes" class="btn btn-danger" asp-route-id="@Model">Delete</a>
    </div>
</td>

OnlineShop/Views/Shared/_Layout.cshtml
@using System.Net.Http
@using OnlineShop.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    var userRole = HttpContextAccessor.HttpContext.Session.GetString("roleName");
    int count = 0;
    List<Products> products = HttpContextAccessor.HttpContext.Session.Get<List<Products>>("products");
    if(products==null)
    {
        products = new List<Products>();
    }
    count = products.Count();
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineShop.styles.css" asp-append-version="true" />
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>

    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.3.6/css/buttons.dataTables.min.css" />
   @* datepicker*@
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
  
    <style>
        .error{
            color:red;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        @if(userRole=="Customer")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="ProductType" asp-action="Index">Product Type</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="SpecialTag" asp-action="Index">Tag Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Upload">Upload</a>
                            </li>
                            
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Cart">
                                <i class="fas fa-shopping-cart"></i>    (@count)
                            </a>

                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OnlineShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

  

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>
    @* datepicker*@
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>