OnlineShop/Areas/Admin/Controllers/RoleController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineShop.Areas.Admin.Models;
using OnlineShop.Data;
using OnlineShop.Models;

namespace OnlineShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RoleController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<IdentityUser> _userManager;
        ApplicationDbContext _context;

        public RoleController(RoleManager<IdentityRole> roleManager, ApplicationDbContext context,
        UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _context = context;
            _userManager= userManager;


        }
        public IActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();
            ViewBag.Roles = roles;
            return View();
        }
        //Create role get method
        public IActionResult Create()
        {

            return View();
        }
        //Create post method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string name)
        {
            IdentityRole role = new IdentityRole();
            role.Name = name;
            var isExist = await _roleManager.RoleExistsAsync(role.Name);
            if (isExist)
            {
                ViewBag.msg = "This role is already exist";
                ViewBag.name = name;
                return View();
            }
            var result = await _roleManager.CreateAsync(role);
            if (result.Succeeded)
            {
                TempData["Save"] = "Role has been saved successfully";
                return RedirectToAction("Index");
            }
            return View();
        }
        //Edit role get method
        public async Task<IActionResult> Edit(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();

            }
            ViewBag.id = role.Id;
            ViewBag.name = role.Name;
            return View(role);
        }
        //Create post method
        [HttpPost]

        public async Task<IActionResult> Edit(string id, string name)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();

            }
            role.Name = name;
            var isExist = await _roleManager.RoleExistsAsync(role.Name);
            if (isExist)
            {
                ViewBag.msg = "This role is already exist";
                ViewBag.name = name;
                return View();
            }
            var result = await _roleManager.UpdateAsync(role);
            if (result.Succeeded)
            {
                TempData["Save"] = "Role has been update successfully";
                return RedirectToAction("Index");
            }
            return View();
        }
        //Detail  role get method
        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();

            }
            ViewBag.id = role.Id;
            ViewBag.name = role.Name;
            return View(role);
        }
        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();

            }
            var result = await _roleManager.DeleteAsync(role);
            if (result.Succeeded)
            {
                TempData["Save"] = "Role has been deleted successfully";
                return RedirectToAction("Index");
            }

            return View(role);
        }
        public async Task<IActionResult> Assign(string id)
        {
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers.Where(f=>f.LockoutEnd<DateTime.Now||f.LockoutEnd==null), "Id", "UserName");
            ViewData["RoleId"] = new SelectList(_context.Roles.ToList(), "Name", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Assign(RolesUserVm rolesUser)
        {
            var user = _context.ApplicationUsers.FirstOrDefault(c => c.Id == rolesUser.UserId);
            var isCheckedRoleAssign= await _userManager.IsInRoleAsync(user, rolesUser.RoleId);
            if(isCheckedRoleAssign )
            {
                ViewBag.msg= "This User already Assigned this role.";
                return View();
            }
            
            var role = await _userManager.AddToRoleAsync(user,rolesUser.RoleId);
            if(role == null)
            {
                TempData["Save"] = "User Role Assigned.";
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult AssignUserRole()
        {
            //join querey to see the who is assign for which role
            var result = from ur in _context.UserRoles
                         join r in _context.Roles on ur.RoleId equals r.Id
                         join a in _context.ApplicationUsers on ur.UserId equals a.Id
                         select new UserRoleMapping()
                         {
                             UserId = ur.UserId,
                             RoleId = ur.RoleId,
                             UserName = a.UserName,
                             RoleName = r.Name
                         };
            ViewBag.UserRoles = result;
            return View();
        }
    }
}

OnlineShop/Areas/Admin/Views/Role/Assign.cshtml
@model OnlineShop.Areas.Admin.Models.RolesUserVm
@{
    ViewData["Title"] = "Create";
}

<h1 class="text-primary">Assign Role</h1>
<form asp-action="Assign" method="post">
    <div class="p-4 rounded border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <h1 class=" text-danger">@ViewBag.msg</h1>
   
        <div class="form-group row mt-2 ">
            <div class="col-2">
                <label asp-for="UserId"></label>
            </div>
            <div class="col-5">
                <select asp-for="UserId" asp-items="@ViewBag.UserId" class="form-control"></select>
                @*<input asp-for="ProductTypeId" class="form-control" />*@
            </div>
            <span asp-validation-for="UserId" class="text-danger"></span>
        </div>
        <div class="form-group row  mt-2">
            <div class="col-2">
                <label asp-for="RoleId"></label>
            </div>
            <div class="col-5">
                <select asp-for="RoleId" asp-items="@ViewBag.RoleId" class="form-control"></select>
            </div>
            <span asp-validation-for="RoleId" class="text-danger"></span>
        </div>
        
    </div>

    <div class="form-group mt-2">
        <input type="submit" class="btn btn-primary" value="Assign" />
        <a asp-action="Index" class="btn btn-success">Back to List</a>
    </div>

</form>

OnlineShop/Areas/Admin/Views/Role/AssignUserRole.cshtml
@{
    ViewData["Title"] = "Assign User Role";
}
<br />
<br />

<div class="row">
    <div class="col-6">
        <h2 class="text-primary">Assign User Roles</h2>
    </div>
    @*<div class="col-6">
        <a asp-action="Create" class="btn btn-primary">New Role</a>
    </div>*@
</div>
<br />
<div>
    <table class="table table-stropped border text-center">
        <thead>
            <tr class="table-info">
                <th>User Name</th>
                <th>Role Name</th>

            </tr>
        </thead>
        <tbody>

            @foreach (var item in ViewBag.UserRoles)

            {
                <tr>
                    <td>@item.UserName </td>
                    <td>@item.RoleName </td>
                   

                </tr>
            }

        </tbody>
    </table>
</div>

OnlineShop/Areas/Admin/Views/Role/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

<h1 class="text-primary">Add New Role</h1>
<form asp-action="Create" method="post" id="user-form" enctype="multipart/form-data">
    <div class="p-4 rounded border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @* <h1 class="alert alert-warning">@ViewBag.message</h1>*@
        <h3 class="text-danger">@ViewBag.msg</h3>
        <div class="form-group row">
            <div class="col-2 ">
                <label>Role Name</label>
            </div>
            <div class="col-5">
                <input id="name" name="name" value="@ViewBag.name" class="form-control" required />
            </div>
            
        </div>

    </div>

    <div class="form-group mt-2">
        <input type="submit" class="btn btn-primary" value="Save" />
        <a asp-action="Index" class="btn btn-success">Back to List</a>
    </div>

</form>

OnlineShop/Areas/Admin/Views/Role/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}

<h1 class="text-primary">Delete Role</h1>
<form asp-action="Delete" method="post" >
    <div class="p-4 rounded border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @* <h1 class="alert alert-warning">@ViewBag.message</h1>*@
        <h3 class="text-danger">Do you want to Delete?</h3>
        <div class="form-group row">
            <div class="col-2 ">
                <label>Role Name</label>
            </div>
            <input type="hidden" value="@ViewBag.id" name="id" />
            <div class="col-5">
                <input id="name" name="name" value="@ViewBag.name" readonly="readonly" class="form-control" required />
            </div>

        </div>

    </div>

    <div class="form-group mt-2">
        <input type="submit" class="btn btn-primary" value="Delete" />
        <a asp-action="Index" class="btn btn-success">Back to List</a>
    </div>

</form>

OnlineShop/Areas/Admin/Views/Role/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-primary">Edit New Role</h1>
<form asp-action="Edit" method="post" id="user-form" enctype="multipart/form-data">
    <div class="p-4 rounded border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @* <h1 class="alert alert-warning">@ViewBag.message</h1>*@
        <h3 class="text-danger">@ViewBag.msg</h3>
        <div class="form-group row">
            <div class="col-2 ">
                <label>Role Name</label>
            </div>
            <input type="hidden" value="@ViewBag.id" name="id" />
            <div class="col-5">
                <input id="name" name="name" value="@ViewBag.name" class="form-control" required />
            </div>

        </div>

    </div>

    <div class="form-group mt-2">
        <input type="submit" class="btn btn-primary" value="Update" />
        <a asp-action="Index" class="btn btn-success">Back to List</a>
    </div>

</form>

OnlineShop/Areas/Admin/Views/Role/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<br />
<br />

<div class="row">
    <div class="col-6">
        <h2 class="text-primary">Roles</h2>
    </div>
    <div class="col-6">
        <a asp-action="Create" class="btn btn-primary">New Role</a>
    </div>
</div>
<br />
<div>
    <table class="table table-stropped border text-center">
        <thead>
            <tr class="table-info">
                <th>Name</th>
               
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
           
                    @foreach (var item in ViewBag.Roles)

                    {
                    <tr>
                        <td>@item.Name </td>
                        <td>
                            <a asp-action="Edit" asp-controller="Role" class="btn btn-success btn-sm" asp-route-id="@item.Id"><i class='fas fa-edit'></i></a>
                            @*<a asp-action="Detail" asp-controller="Role" class="btn btn-info btn-sm" asp-route-id="@item.Id"><i class='fas fa-th-list'></i></a>*@
                            <a asp-action="Delete" asp-controller="Role" class="btn btn-danger btn-sm" asp-route-id="@item.Id"><i class='fas fa-trash-alt'></i></a>
                        </td>


                    </tr>
                    }
               
        </tbody>
    </table>
</div>